[package]
name = "test_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
prost = "0.5"
prost-types = "0.5"

[build-dependencies]
prost-build = { version = "0.5" }