[package]
name = "test_url"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = { version = "2.2.2", features = ["serde"] }
percent-encoding = "2.1.0"
base64 = "0.13.0"