// mod stack_heap;
// mod vars;
// mod ownership;
// mod generics;
mod lifetime;
// mod structs;
// mod enums;
// mod traits;
// mod error_handling;
// mod debug;
// mod unit_test;
// extern crate lib_demo;
// mod three_five;
// mod three;
// mod hashmap;
// mod eight;
// mod eight_three;
// mod threeteen;
// mod iteretor;
// mod deref;
// mod drop;
// mod rc;
// mod thread;
// mod oop;
// mod eighteen;

fn main() {
  // vars::run();
  // stack_heap::run();
  // ownership::run();
  // generics::run();
  lifetime::run();
  // structs::run();
  // enums::run();
  // traits::run();
  // error_handling::run();
  // debug::run();
  // lib_demo::print_random_number();
  // three_five::run();
  // three::run();
  // hashmap::run();
  // eight::run();
  // // eight_three::run();
  // threeteen::run();
  // iteretor::run();
  // deref::run();
  // drop::run();
  // rc::run();
  // thread::run();
  // thread::run3();
  // oop::run();
  // eighteen::run();
  // eighteen::run2();
  // eighteen::run3();
  // eighteen::run4();
  // eighteen::run5();
  // eighteen::run6();
  // eighteen::run7();
  // eighteen::run8();
  // eighteen::run9();
}
