// mod stack_heap;
// mod vars;
// mod ownership;
// mod generics;
// mod lifetime;
// mod structs;
// mod enums;
// mod traits;
// mod error_handling;
// mod debug;
// mod unit_test;
// extern crate lib_demo;
// mod three_five;
// mod three;
// mod hashmap;
// mod eight;
// mod eight_three;
// mod threeteen;
mod iteretor;

fn main() {
  // vars::run();
  // stack_heap::run();
  // ownership::run();
  // generics::run();
  // lifetime::run();
  // structs::run();
  // enums::run();
  // traits::run();
  // error_handling::run();
  // debug::run();
  // lib_demo::print_random_number();
  // three_five::run();
  // three::run();
  // hashmap::run();
  // eight::run();
  // // eight_three::run();
  // threeteen::run();
  iteretor::run();
}
