CREATE TABLE posts (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  evaluation_point VARCHAR(255) NOT NULL,
  skill_point VARCHAR(255) NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0
) DEFAULT CHARACTER SET= utf8mb4;