CREATE TABLE users (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  mail_address VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  enable BOOLEAN NOT NULL DEFAULT 1
) DEFAULT CHARACTER SET= utf8mb4;